const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Plugins.Touch,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.TiledBg.Exps.ImageOffsetX,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetFlipped,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.Touch.Cnds.IsTouchingObject
	];
};
self.C3_JsPropNameTable = [
	{BG: 0},
	{Solid: 0},
	{Piso: 0},
	{Piso2: 0},
	{Platform: 0},
	{Aviao: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Keyboard: 0},
	{Text: 0},
	{Text2: 0},
	{Sprite3: 0},
	{Text3: 0},
	{Text4: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{botton: 0},
	{Touch: 0},
	{Text5: 0},
	{Bala: 0},
	{Text6: 0},
	{Text7: 0},
	{Text8: 0}
];

self.InstanceType = {
	BG: class extends self.ITiledBackgroundInstance {},
	Piso: class extends self.ITiledBackgroundInstance {},
	Piso2: class extends self.ITiledBackgroundInstance {},
	Aviao: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Text: class extends self.ITextInstance {},
	Text2: class extends self.ITextInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Text3: class extends self.ITextInstance {},
	Text4: class extends self.ITextInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	botton: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Text5: class extends self.ITextInstance {},
	Bala: class extends self.ISpriteInstance {},
	Text6: class extends self.ITextInstance {},
	Text7: class extends self.ITextInstance {},
	Text8: class extends self.ITextInstance {}
}